const flagMarkers = [
  { country: "South Korea", lat: 35.1, lng: 129.0, file: "KR.gif" },
  { country: "Japan", lat: 35.6, lng: 139.7, file: "JP.gif" },
  { country: "China", lat: 24.0, lng: 110.0, file: "CN.gif" },
  { country: "Vietnam", lat: 16.0, lng: 108.0, file: "VN.gif" },
  { country: "Singapore", lat: 1.25, lng: 103.85, file: "SG.gif" },
  { country: "Indonesia", lat: -6.2, lng: 106.8, file: "ID.gif" },
  { country: "India", lat: 22.6, lng: 78.4, file: "IN.gif" },
  { country: "Sri Lanka", lat: 7.0, lng: 81.0, file: "LK.gif" },
  { country: "Yemen", lat: 12.0, lng: 45.0, file: "YE.gif" },
  { country: "Ethiopia", lat: 9.0, lng: 38.0, file: "ET.gif" },
  { country: "Egypt", lat: 26.0, lng: 31.0, file: "EG.gif" },
  { country: "Libya", lat: 27.0, lng: 17.0, file: "LY.gif" },
  { country: "Greece", lat: 38.0, lng: 23.7, file: "GR.gif" },
  { country: "Italy", lat: 41.9, lng: 12.5, file: "IT.gif" },
  { country: "Monaco", lat: 43.7, lng: 7.4, file: "MC.gif" },
  { country: "Spain", lat: 36.8, lng: -5.5, file: "ES.gif" },
  { country: "Morocco", lat: 31.8, lng: -7.1, file: "MA.gif" },
  { country: "Algeria", lat: 28.0, lng: 1.6, file: "DZ.gif" },
  { country: "UK", lat: 51.5, lng: -0.1, file: "GB.gif" },
  { country: "USA", lat: 25.7, lng: -80.2, file: "US.gif" },
  { country: "Colombia", lat: 4.6, lng: -74.1, file: "CO.gif" },
  { country: "Venezuela", lat: 10.5, lng: -66.9, file: "VE.gif" },
  { country: "Ecuador", lat: -2.2, lng: -79.9, file: "EC.gif" },
  { country: "Saudi Arabia", lat: 24.7, lng: 46.7, file: "SA.gif" },
  { country: "Portugal", lat: 39.4, lng: -9.1, file: "PT.gif" },
  { country: "Somalia", lat: 2.0, lng: 45.3, file: "SO.gif" },
  { country: "Panama", lat: 8.98, lng: -79.52, file: "PA.gif" },
  { country: "Malaysia", lat: 3.14, lng: 101.69, file: "MY.gif" }
];